name: foody
description: A Flutter app for image analysis with user health metrics.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  get_it: ^7.6.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.2
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  meta: ^1.9.1
  google_fonts: ^4.0.3
  http_parser: ^4.0.2
  fl_chart: ^0.65.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.5.0
  mobile_scanner: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
