name: foody
description: A Flutter app for image analysis with user health metrics.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_messaging: ^16.0.2
  google_sign_in: ^7.2.0  
  provider: ^6.0.5
  get_it: ^8.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.2
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  flutter_spinkit: ^5.2.0
  meta: ^1.9.1
  google_fonts: ^6.3.2
  http_parser: ^4.0.2
  fl_chart: ^1.1.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.5.0
  mobile_scanner: ^7.1.2
  intl: ^0.20.2
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  dio: ^5.9.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.15.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
